'use strict';

/**
 * The admin Mail page: what the app sends, what it looks like, and what
 * actually left the building.
 *
 * Admin-only. Rendered previews come straight from utils/emailMessages.js, so
 * what an admin reviews here is byte-for-byte what a client receives.
 */

const express = require('express');
const router = express.Router();

const { db } = require('../db/setup');
const { requireAuth, requireRole, requireCSRF, audit } = require('../middleware/auth');
const mailer = require('../utils/mailer');
const messages = require('../utils/emailMessages');
const admins = require('../utils/admins');
const slaWatch = require('../utils/slaWatch');
const domainWatch = require('../utils/domainWatch');

router.use(requireAuth, requireRole('admin'));

router.get('/status', async (req, res, next) => {
  try {
    const inboxes = await admins.adminEmails();
    res.json({
      configured: mailer.isEnabled(),
      transport: mailer.transportName(),
      from: mailer.fromAddress(),
      adminInboxes: inboxes,
      adminCount: await admins.countAdmins(),
      extraRecipients: mailer.adminRecipients(),
      smtp: mailer.smtpSummary(),
    });
  } catch (err) {
    next(err);
  }
});

router.get('/templates', (req, res) => {
  res.json({ templates: messages.listTemplates() });
});

/** JSON preview: subject, HTML, and the plain-text twin side by side. */
/**
 * A browser cannot resolve cid: -- those only exist inside a sent message.
 * Point them at the same files on this server so the on-page preview shows
 * the artwork an inbox will actually get.
 */
function previewable(html) {
  return String(html || '')
    // Match the full asset name: hyphens ("web-corner") and digits ("bar-030")
    // both appear in it. A narrower class stops mid-name and yields a 404.
    .replace(/cid:ethixweb-icon-([a-z0-9-]+)/g, '/mail-icons/$1.png')
    .replace(/cid:ethixweb-logo/g, '/ethixweb.png');
}

/**
 * The policy the two HTML preview routes serve themselves under.
 *
 * Setting this header replaces helmet's entirely rather than adding to it, so
 * every directive these documents need has to be named here -- `frame-ancestors`
 * included. Leaving it out dropped the clickjacking guard from the only two
 * pages in the app that render stored, third-party-influenced markup.
 *
 * `img-src 'self'` matters in development: the preview loads the emblem from
 * this same origin over plain http, which an https-only img-src silently blocks.
 */
const PREVIEW_CSP = [
  "default-src 'none'",
  "style-src 'unsafe-inline'",
  "img-src 'self' data: https:",
  "frame-ancestors 'self'",
  "base-uri 'none'",
  "form-action 'none'",
].join('; ');

router.get('/templates/:key/preview', (req, res) => {
  const preview = messages.renderPreview(req.params.key);
  if (!preview) return res.status(404).json({ error: 'Unknown email template' });
  res.json({ ...preview, html: previewable(preview.html) });
});

/**
 * The same preview as a real HTML document, for an iframe.
 *
 * Served with a sandbox-friendly CSP of its own: the markup is generated by
 * this app, but rendering it in a frame should still be able to do nothing
 * except display text.
 */
router.get('/templates/:key/preview.html', (req, res) => {
  const preview = messages.renderPreview(req.params.key);
  if (!preview) return res.status(404).send('Unknown email template');
  res.set('Content-Type', 'text/html; charset=utf-8');
  res.set('Content-Security-Policy', PREVIEW_CSP);
  res.send(previewable(preview.html));
});

/** Newest first. The stored HTML is dropped here to keep the list light. */
router.get('/log', async (req, res, next) => {
  try {
    const limit = Math.min(Math.max(Number(req.query.limit) || 100, 1), 500);
    const rows = await mailer.recentLog(limit);
    res.json({
      entries: rows.map(({ html, ...rest }) => ({ ...rest, hasHtml: Boolean(html) })),
      configured: mailer.isEnabled(),
    });
  } catch (err) {
    next(err);
  }
});

/** One logged message, including exactly what was rendered. */
router.get('/log/:id', async (req, res, next) => {
  try {
    const entry = await db.find('email_log', req.params.id);
    if (!entry) return res.status(404).json({ error: 'No such message' });
    res.json({ entry });
  } catch (err) {
    next(err);
  }
});

router.get('/log/:id/body.html', async (req, res, next) => {
  try {
    const entry = await db.find('email_log', req.params.id);
    if (!entry) return res.status(404).send('No such message');
    res.set('Content-Type', 'text/html; charset=utf-8');
    res.set('Content-Security-Policy', PREVIEW_CSP);
    res.send(entry.html || '<p style="font-family:sans-serif;padding:24px;">This message was logged without a stored body.</p>');
  } catch (err) {
    next(err);
  }
});

/**
 * Check the credentials without sending anything. For SMTP this opens a real
 * connection and authenticates, so a wrong password fails here rather than
 * silently on the first ticket.
 */
router.post('/verify', requireCSRF, async (req, res, next) => {
  try {
    const result = await mailer.verifyTransport();
    await audit(req.user.id, 'update', 'email_transport', result.transport, { ok: result.ok });
    if (!result.ok) return res.status(502).json(result);
    res.json(result);
  } catch (err) {
    next(err);
  }
});

/** Fire a real message at an inbox to prove the transport works end to end. */
router.post('/test', requireCSRF, async (req, res, next) => {
  try {
    const to = (req.body?.to || req.user.email || '').trim();
    if (!mailer.isAddress(to)) return res.status(400).json({ error: 'Give a valid email address to send the test to.' });
    if (!mailer.isEnabled()) {
      return res.status(503).json({
        error: 'No email transport is configured. Set SMTP_HOST (plus SMTP_USER and SMTP_PASSWORD), RESEND_API_KEY, or MAIL_WEBHOOK_URL, then restart the server.',
      });
    }

    // An optional template key sends that exact message instead of the generic
    // test one, so an admin can check how a real notification lands in a real
    // inbox rather than trusting the on-page preview.
    const key = req.body?.template || null;
    const message = key ? messages.renderMessage(key) : messages.testEmail({ requestedBy: req.user.name });
    if (!message) return res.status(404).json({ error: 'Unknown email template' });

    const result = await mailer.sendTemplate({
      to,
      message,
      template: key || 'test',
      entity: 'user',
      entityId: req.user.id,
    });
    await audit(req.user.id, 'send', 'email_test', to, { template: key || 'test' });

    if (!result.ok) return res.status(502).json({ error: result.error || 'The message could not be sent.' });
    res.json({ ok: true, to, transport: result.transport });
  } catch (err) {
    next(err);
  }
});

/** Run the first-response deadline sweep now instead of waiting for traffic. */
router.post('/sla-sweep', requireCSRF, async (req, res, next) => {
  try {
    const result = await slaWatch.runSweep();
    await audit(req.user.id, 'send', 'sla_sweep', String(result.warned));
    res.json(result);
  } catch (err) {
    next(err);
  }
});

/** Run the domain expiry sweep now instead of waiting for traffic. */
router.post('/domain-sweep', requireCSRF, async (req, res, next) => {
  try {
    const result = await domainWatch.runSweep();
    await audit(req.user.id, 'send', 'domain_sweep', String(result.sent));
    res.json(result);
  } catch (err) {
    next(err);
  }
});

/**
 * Send a client their progress summary now, rather than waiting for whatever
 * schedule the deployment runs this on.
 */
router.post('/digest/:clientId', requireCSRF, async (req, res, next) => {
  try {
    const client = await db.find('users', req.params.clientId);
    if (!client || client.role !== 'client') return res.status(404).json({ error: 'No such client' });
    if (!mailer.isAddress(client.email)) return res.status(400).json({ error: 'That client has no usable email address.' });

    const [tickets, projects] = await Promise.all([
      db.filter('tickets', (t) => t.clientId === client.id),
      db.filter('projects', (p) => p.clientId === client.id),
    ]);

    const result = await mailer.sendTemplate({
      to: client.email,
      message: messages.progressDigest({
        clientName: client.name,
        tickets,
        projects: projects.map((p) => ({ name: p.name, status: p.status })),
        period: 'this week',
      }),
      template: 'progress_digest',
      entity: 'user',
      entityId: client.id,
    });
    await audit(req.user.id, 'send', 'email_digest', client.id);

    if (!result.ok && !result.skipped) return res.status(502).json({ error: result.error || 'The summary could not be sent.' });
    res.json({
      ok: Boolean(result.ok),
      skipped: result.skipped || null,
      to: client.email,
      redirectedTo: result.redirectedTo || null,
    });
  } catch (err) {
    next(err);
  }
});

module.exports = router;
